errorClass: b-error
loadInvisible: false
offset: 100
saveViewportOffsetDelay: 50
selector: b-lazy
alter_tag:
  img: img
  iframe: 0
skipClass: no-b-lazy
src: data-src
successClass: b-loaded
validateDelay: '25'
placeholderSrc: 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=='
image_fields:
  media--featured_image--default--field_media_image: true
  media--image--default--field_media_image: true
  paragraph--hero--default--field_hero_image: true
  user--user--default--user_picture: true
  user--user--list--user_picture: true
  user--user--full--user_picture: true
  user--user--compact--user_picture: true
disabled_paths: /rss.xml
_core:
  default_config_hash: h_4N5fL4QosXf3JITfYemQOmapK2xYFlwZGOv371LH8
